# env settings
language: node_js
node_js: 9
# travis script adaptions
branches:
  only:
  - master
  - development
  - /^greenkeeper/.*$/

# before_install:
#   - npm install -g 

install:
  - npm install

script:
  - npm run test
